version: '3.5' 
services:
    webpack-typescript-starter:
      build: 
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/usr/src/app' 
      ports: 
        - '4000:8080'
